### ISSUE TITLE
Docs - IsLiveReloading

### ISSUE THREAD

**Issue by dud3** [SiliconStudio/xenko-docs#11]
The first result <a href='https://www.google.no/search?q=how+to+install+fonts+in+windows+10&oq=ho&aqs=chrome.0.69i59j69i60l2j69i61j69i57j0.255j0j7&sourceid=chrome&ie=UTF-8#q=xenko+IsLiveReloading'>here</a> Is pointing to the wrong/non-existing document I guess: http://doc.xenko.com/1.4/api/P_SiliconStudio_Xenko_Engine_Script_IsLiveReloading.html

What would be the alternative?
Also could we possibly tell google to not give us wrong links?

Thanks.

**Comment by Kryptos-FR** [comment]
That would be this link: http://doc.xenko.com/1.4/api/SiliconStudio.Xenko.Engine.Script.html#SiliconStudio_Xenko_Engine_Script_IsLiveReloading

Also you might now want to go to the latest version (since the API for script changed a bit): http://doc.xenko.com/latest/api/SiliconStudio.Xenko.Engine.ScriptComponent.html#SiliconStudio_Xenko_Engine_ScriptComponent_IsLiveReloading

Google probably had cached an old version of the documentation, hence the wrong link. Their cache get refreshed periodically so hopefully "wrong" links tend to be removed at some point.

**Comment by dud3** [comment]
Thanks. Feel free to close this issue. =)
